### ISSUE TITLE
setmessage not working

### ISSUE THREAD

**Issue by viki2910** [Shashank02051997/FancyGifDialog-Android#12]

**Comment by viki2910** [comment]
no message is displayed
![issue](https://user-images.githubusercontent.com/37739139/69083134-7dff1600-0a67-11ea-81e3-7abb03d91171.jpeg)

**Comment by viki2910** [comment]
how to resolve this error

**Comment by nsalleron** [comment]
can we have an code example of your issue ?

**Comment by l132a** [comment]
How to fix it in dark mode ?, The message cannot be displayed

**Comment by Shashank02051997** [comment]
This lib have some issue in dark mode so that's why it is not showing the setMessage content

**Comment by Shashank02051997** [comment]
I have given the functionality to set title and description color so I am closing this issue
