### ISSUE TITLE
Not working in fragment

### ISSUE THREAD

**Issue by stateman92** [Shashank02051997/FancyGifDialog-Android#13]
I want to use it in a fragment. I get this error:

java.lang.ClassCastException: android.graphics.drawable.RippleDrawable cannot be cast to android.graphics.drawable.GradientDrawable

How can I solve it?

**Comment by stateman92** [comment]
I found out that this is a bug in the lib: FancyGifDialog.java, 134. line. So the color doesn't matter, it fails in the code of the lib.

**Comment by Shashank02051997** [comment]
@stateman92 I am closing this issue. Please feel free to reopen it again
