### ISSUE TITLE
same issue #12 (set message not working )

### ISSUE THREAD

**Issue by saechimdaeki** [Shashank02051997/FancyGifDialog-Android#14]
![image](https://user-images.githubusercontent.com/40031858/76590008-53adf880-652f-11ea-87f7-d247052a9373.png)

and my code 

<code>

   
                @Override
                     public void onBindViewHolder(@NonNull batsal_testAdapter.ItemViewHolder holder, 
             final int position) {
             holder.onBind(listData.get(position));
            holder.mview.setOnClickListener(new View.OnClickListener() {
            @Override
            public void onClick(View view) {
                Context context=view.getContext();
                Intent intent=new Intent(context, Training_batsal.class);
                if(position==0){
                    /* source this library:  https://github.com/Shashank02051997/FancyGifDialog-Android   
                */
                    new FancyGifDialog.Builder((Activity)context)
                            .setTitle("하이 니즈")
                            .setMessage("무릎이 위로 올라가도록 abcdabcd ")
                            .setNegativeBtnText("Cancel")
                            .setPositiveBtnBackground("#FF4081")
                            .setPositiveBtnText("Ok")
                            .setNegativeBtnBackground("#FFA9A7A8")
                            .setGifResource(R.drawable.gif1)   //Pass your Gif here
                            .isCancellable(true)
                            .OnPositiveClicked(new FancyGifDialogListener() {
                                @Override
                                public void OnClick() {
                                   // Toast.makeText(MainActivity.this,"Ok",Toast.LENGTH_SHORT).show();
                                }
                            })
                            .OnNegativeClicked(new FancyGifDialogListener() {
                                @Override
                                public void OnClick() {
                                    //Toast.makeText(MainActivity.this,"Cancel",Toast.LENGTH_SHORT).show();
                                 }
                                })
                            .build();
                     }
   
                  }
                     });
             }

</code>

**Comment by stateman92** [comment]
Same issue, maybe it's a bug in the lib.

**Comment by saechimdaeki** [comment]
@stateman92  haha So I am writing a long title message.

![image](https://user-images.githubusercontent.com/40031858/76639630-ce0f6480-6591-11ea-87ee-e94cc40cc9a4.png)

**Comment by Shashank02051997** [comment]
@saechimdaeki @stateman92 yes it does not work if app is running in dark mode

**Comment by Shashank02051997** [comment]
I have given the functionality to set title and description color so I am closing this issue... A new version is available please check and update your dependency

**Comment by saechimdaeki** [comment]
@Shashank02051997  Thank you for your constant update. I'll use it well.
