### ISSUE TITLE
Message gets invisible in dark mode.

### ISSUE THREAD

**Issue by fantasticrahulrai** [Shashank02051997/FancyGifDialog-Android#19]
Add support for dark mode. Message text disappears in the dark mode. Atleast provide a method to change textcolor so that we can use daynight resources.

**Comment by achayan** [comment]
Facing same problem, dark mode we can't read the text. Is there any plan to implement a function for that ?

**Comment by Shashank02051997** [comment]
@fantasticrahulrai @achayan I will the lib and give the support of change the text color

**Comment by Shashank02051997** [comment]
I have given the functionality to set title and description color so I am closing this issue... A new version is available please check and update your dependency
