### ISSUE TITLE
Handle OnPositiveClicked 

### ISSUE THREAD

**Issue by salimido** [Shashank02051997/FancyGifDialog-Android#7]
hello,
is it possible to override the **OnPositiveClicked**, i want it to change the **GifResource** for 2 seconds before closing the dialog.

Thank you, very good library

**Comment by Shashank02051997** [comment]
Can you please elaborate more. I am not understanding what you mean?

**Comment by Shashank02051997** [comment]
Hey, @salimido I was checking for a long time but not found out anything regarding your query so I am closing the issue, and if someone able to do the same I am happy to merge that PR in our master branch.
