### ISSUE TITLE
Not working in a fragment

### ISSUE THREAD

**Issue by ovicko** [Shashank02051997/FancyGifDialog-Android#9]
When I pass `getActivity()` in `new FancyAlertDialog.Builder(getActivity())` no error though it doesn't show up

**Comment by Shashank02051997** [comment]
I will try to fix this on the next version of this lib.

**Comment by Shashank02051997** [comment]
@ovicko try to use the new release of this lib and let me know it gets fixed or not.

**Comment by Shashank02051997** [comment]
I'm closing this issue for now... if you again face the issue reopen it
